支持天选、红包与热门推荐推送到QQ群
Deliay/Mikibot pull request #3
Opened 2022-06-28 05:13 UTC by xfoxfu

2022-06-28 06:23 UTC, Deliay requested changes

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/Http/Bilibili/BiliLiveCrawler.cs
> +using Mikibot.Crawler.Http.Bilibili.Model;
提交的时候禁用掉CRLF转换吧，或者用vscode提交

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/Program.cs
> +using Microsoft.Extensions.DependencyInjection;
提交的时候禁用掉CRLF转换吧，或者用vscode提交

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/WebsocketCrawler/Data/Commands/CommandBase.cs
> +﻿using Mikibot.Crawler.WebsocketCrawler.Data.Commands.KnownCommand;
提交的时候禁用掉CRLF转换吧，或者用vscode提交

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/WebsocketCrawler/Data/Commands/KnownCommand/AnchorLotAward.cs
> +    public byte AwardDontPopup { get; set; }
property之间的换行

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/WebsocketCrawler/Data/Commands/KnownCommand/AnchorLotStart.cs
> +    public string AssetIconUrl { get; set; }
property之间的换行

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/WebsocketCrawler/Data/Commands/KnownCommand/HotRankSettlementV2.cs
> +    public int Rank { get; set; }
property之间的换行

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/WebsocketCrawler/Data/Commands/KnownCommand/HotRankSettlementV2.cs
> +// {"cmd":"HOT_RANK_SETTLEMENT_V2","data":{"rank":8,"uname":"奈奈莉娅Channel","face":"http://i2.hdslb.com/bfs/face/96ced1f35b9db0feb5200ad075bfe9fb0b6dfe31.jpg","timestamp":1656390300,"icon":"https://i0.
移除无用注释

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Crawler/WebsocketCrawler/Data/Commands/KnownCommand/PopularityRedPocketStart.cs
> +    public int LotId { get; set; }
property之间的换行

2022-06-28 06:23 UTC, Deliay commented on Mikibot.Analyze/Bot/MikiLiveEventProxyService.cs
> +        await MiraiService.SendMessageToAllGroup(default, new MessageBase[]
这个建议发直播间弹幕里是不是更好，哪天我接一个弹幕机器人

2022-06-28 17:10 UTC, xfoxfu commented on Mikibot.Analyze/Bot/MikiLiveEventProxyService.cs
> +        await MiraiService.SendMessageToAllGroup(default, new MessageBase[]
直播的时候如果是网页会自动弹窗的，感觉弹幕机器人没必要。

2022-06-30 05:54 UTC, Deliay commented on Mikibot.Analyze/Bot/MikiLiveEventProxyService.cs
> +        await MiraiService.SendMessageToAllGroup(default, new MessageBase[]
确实

2022-06-30 05:54 UTC, Deliay approved these changes

2022-06-30 05:55 UTC, merged